#!/bin/bash

if [[ -f "$1" ]]; then # Test if a file with the name from the first argument exits
	echo "It's a file!"
elif [[ -d "$1" ]]; then # If no file is found, test if a directory with the name from the first argument exists
	echo "It's a directory"
else # If no file or directory with the name of the first argument is found, print an error
	echo "Not found: $1"
fi
